version: '3'

tasks:
  build:
    desc: Build the go binary.
    cmds:
      - go build -o bin/walk -i cmd/walk/main.go
  test:
    desc: Run all the go tests.
    cmds:
      - go test -count=1 ./...
  testv:
    desc: Run all the go tests verbose.
    cmds:
      - go test -count=1 ./... -v
